### ISSUE TITLE
Changing theme at runtime not working

### ISSUE THREAD

**Issue by DenZuck** [spiegelp/MaterialDesignExtensions#37] opened 2019-05-09 16:21 UTC
Hi,
I'm trying to change the theme at runtime but when I apply the new theme by replacing .xaml resources the SideNavigation shows no items.

Before changing theme
![image](https://user-images.githubusercontent.com/7376037/57468977-d918aa80-7285-11e9-956d-81771617f2d8.png)

After changing theme
![image](https://user-images.githubusercontent.com/7376037/57469047-fea5b400-7285-11e9-9c91-f439e89ae8e7.png)

In app.xaml I have
```javascript
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/Generic.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesignDarkTheme.xaml" />
```
 
 
This is the function I use to change theme

```javascript
        public void SetLightDark(bool isDark)
        {
            //new PaletteHelper().SetLightDark(isDark);

            var resources = Application.Current.Resources.MergedDictionaries;

            foreach (var res in resources)
            {
                if (res.Source != null)

                Console.WriteLine(res.Source.AbsolutePath);
            }

            var existingResourceDictionary = Application.Current.Resources.MergedDictionaries
                                            .Where(rd => rd.Source != null)
                                            .SingleOrDefault(rd => Regex.Match(rd.Source.OriginalString, @"(\/MaterialDesignExtensions;component\/Themes\/MaterialDesign((Light)|(Dark))Theme)").Success);

            if (existingResourceDictionary == null)
                throw new ApplicationException("Unable to find Light/Dark base theme in Application resources.");

            var source = $"pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesign{(isDark ? "Dark" : "Light")}Theme.xaml";
            var newResourceDictionary = new ResourceDictionary() { Source = new Uri(source) };

            Application.Current.Resources.MergedDictionaries.Remove(existingResourceDictionary);
            Application.Current.Resources.MergedDictionaries.Add(newResourceDictionary);
        }
```
Example project to reproduce the problem
[TestMaterialExtensions.zip](https://github.com/spiegelp/MaterialDesignExtensions/files/3163056/TestMaterialExtensions.zip)

**Comment by spiegelp** [comment] 2019-05-12 10:43
@DenZuck Changing the theme at runtime has the side effect that the resources of the controls will be removed too. I will fix this issue with the next release.

**Comment by DenZuck** [comment] 2019-05-12 12:27
Ok, thanks.

I have noticed that if I declare m_navigationItems as ObservableCollection and add items after the menu is rendered, when I refresh the NavigationItems field I get errors:
```javascript
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionBackground; DataItem=null; target element is 'Border' (Name=''); target property is 'Background' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionForeground; DataItem=null; target element is 'ContentControl' (Name=''); target property is 'Foreground' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionForeground; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Foreground' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionBackground; DataItem=null; target element is 'Border' (Name=''); target property is 'Background' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionForeground; DataItem=null; target element is 'ContentControl' (Name=''); target property is 'Foreground' (type 'Brush')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionForeground; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Foreground' (type 'Brush')
```
I have another question, is there a way to abort the navigation? Suppose user is in Item1 that require data to be saved. When user click in item2 it would be great to show a dialog box "save data?" with buttons YES, NO, CANCEL. If user press CANCEL no navigation should be happen.

**Comment by spiegelp** [comment] 2019-05-14 20:12
@DenZuck Hi

1. I uploaded a pre-release some moments ago solving the bug concerning the theme change at runtime. I introduced the helper `MaterialDesignExtensions.Themes.PaletteHelper` to do all the necessary stuff to change the theme. It is like the one of Material Design in XAML. You can use it to change the theme with one line of code.

2. Abort navigation: `SideNavigation` has a `WillSelectNavigationItemEvent` event, a `WillSelectNavigationItemCommand` command and a `WillSelectNavigationItemCallbackAsync` callback. All of them will be raised/called right after selecting an item and before doing the navigation. All of them provide a way to abort the navigation. Have a look at [NavigationViewModel.cs](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/ViewModel/NavigationViewModel.cs) and [NavigationControl.xaml.cs](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/NavigationControl.xaml.cs) of the demo.

3. I hope to find some time to check the error with `NavigationItems` soon.

**Comment by spiegelp** [comment] 2019-05-22 19:26
@DenZuck 

```wpf
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MaterialDesignExtensions.Controls.SideNavigation', AncestorLevel='1''. BindingExpression:Path=SelectionBackground; DataItem=null; target element is 'Border' (Name=''); target property is 'Background' (type 'Brush')
```

is caused by old items of the list. They were removed from their `ItemsControl`, but the item template is still trying to bind to it. There is no visual parent control anymore and WPF logs this as warning/error in debug mode. I do not know how to prevent this behavior. However it is harmless, because WPF already catches it. See the following two links: 
* [https://stackoverflow.com/questions/47391020/cannot-find-source-for-binding-with-reference-relativesource-findancestor](https://stackoverflow.com/questions/47391020/cannot-find-source-for-binding-with-reference-relativesource-findancestor)
* [https://weblogs.asp.net/akjoshi/resolving-un-harmful-binding-errors-in-wpf](https://weblogs.asp.net/akjoshi/resolving-un-harmful-binding-errors-in-wpf)

**Closed by spiegelp** 2019-05-22 19:26 UTC
Labels: bug, help wanted

**Comment by DenZuck** [comment] 2019-05-22 20:41
@spiegelp hi,

1) I've tried theme changing and it works perfectly
2) I'll have a look at the event and callbacks
3) Ok, as you said it's just an harmless worning

Thanks for the support.
