### ISSUE TITLE
Exception on OpenFileDialog.ShowDialogAsync

### ISSUE THREAD

**Issue by maxmontgmx** [spiegelp/MaterialDesignExtensions#69] opened 2020-01-09 12:50 UTC
Hi all,
I get a similar issue than #20  but the inner exception is different.
I'm using :
package id="MaterialDesignColors" version="1.2.1" targetFramework="net46"
package id="MaterialDesignExtensions" version="2.8.0" targetFramework="net462"
package id="MaterialDesignThemes" version="3.0.0" targetFramework="net46"

The expection detail is :
System.Windows.Media.Animation.AnimationException
HResult=0x80131501
Message=Impossible d'animer la propriété sur un(e) 'IsOpen' d'un(e) 'ControlzEx.PopupEx' à l'aide d'un(e) 'System.Windows.Media.Animation.BooleanAnimationUsingKeyFrames'. Pour plus d'informations, consultez l'exception interne.
Source=PresentationCore
Arborescence des appels de procédure :
à System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
à System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
à System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
à System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
à System.Windows.Media.Animation.TimeManager.Tick()
à System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
à System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
à System.Windows.Threading.DispatcherOperation.InvokeImpl()
à System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
à System.Windows.Threading.DispatcherOperation.Invoke()
à System.Windows.Threading.Dispatcher.ProcessQueue()
à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
à System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
à System.Windows.Application.RunDispatcher(Object ignore)
à System.Windows.Application.RunInternal(Window window)
à System.Windows.Application.Run(Window window)
à System.Windows.Application.Run()
à TestSupervisor.App.Main()

Exception interne 1 :
XamlParseException : L'initialisation de 'MaterialDesignExtensions.Controls.OpenFileControl' a levé une exception.

Exception interne 2 :
NotImplementedException : La méthode ou l'opération n'est pas implémentée.

Thanks for yor help

**Comment by spiegelp** [comment] 2020-01-09 21:12
Duplicate of #67

**Comment by spiegelp** [comment] 2020-01-09 21:14
@maxmontgmx You got a `NotImplementedException` as inner exception. I think that's a duplicate of issue #67. Please look at my answer there.

**Closed by spiegelp** 2020-01-09 21:14 UTC
