### ISSUE TITLE
Animation Exception when opening the OpenFileDialog

### ISSUE THREAD

**Issue by quicoli** [spiegelp/MaterialDesignExtensions#20] opened 2018-08-10 13:24 UTC
Hello,

I'm using MaterialDesingTheme 2.4.1 and MaterialDesignExtensions 2.2.0

The following exception is raised when I try:

```
        internal async Task OpenFile()
        {
            OpenFileDialogArguments dialogArgs = new OpenFileDialogArguments()
            {
                Width = 600,
                Height = 400,
                Filters = "All files|*.*|C# files|*.cs|XAML files|*.xaml"
            };

            OpenFileDialogResult result = await OpenFileDialog.ShowDialogAsync("RootDialog", dialogArgs);
        }
```

System.Windows.Media.Animation.AnimationException: 'Cannot animate the 'IsOpen' property on a 'ControlzEx.PopupEx' using a 'System.Windows.Media.Animation.BooleanAnimationUsingKeyFrames'. For details see the inner exception.'
System.Windows.Media.Animation.AnimationException
  HResult=0x80131501
  Message=Cannot animate the 'IsOpen' property on a 'ControlzEx.PopupEx' using a 'System.Windows.Media.Animation.BooleanAnimationUsingKeyFrames'. For details see the inner exception.
  Source=PresentationCore
  StackTrace:
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Ctacs.LogViewer.App.Main()

Inner Exception 1:
XamlParseException: Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.

Inner Exception 2:
Exception: Cannot find resource named 'MaterialDesignComboBox'. Resource names are case sensitive.

**Comment by spiegelp** [comment] 2018-08-11 18:47
Hi, have a look at _Inner Exception 2: Exception: Cannot find resource named 'MaterialDesignComboBox'. Resource names are case sensitive_. 

I guess you forgot a setup in your application resources. The dialog uses a combo box, but WPF cannot find its style. Please compare your code with the configuration of the demo project in [App.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/App.xaml). 

Please let me know if this resolves your issue.

**Comment by spiegelp** [comment] 2018-09-26 19:47
I closed this issue, because I cannot find a general bug in the library. If the issue still exists please provide a full code example to reproduce the exception.

**Comment by cpyfferoen** [comment] 2018-12-31 22:21
I'm having the same issue for Cannot find resource named 'MaterialDesignComboBox'. Resource names are case sensitive ResourceDictionary (Styles.xaml) follows. I have tried multiple variations. Unlikely.. but perhaps it has to do with using a newer Themes (2.5.0.1205) and an older Extensions (2.4.0 w/ dependency >= 2.3.1.953)??
`<ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.LightBlue.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.LightGreen.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />

        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/Generic.xaml" />

        <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/Generic.xaml" />
    </ResourceDictionary.MergedDictionaries>`

**Comment by spiegelp** [comment] 2019-01-25 14:16
@cpyfferoen Your configuration misses styles. Do you still have the issue if you replace your App.xaml with the one out of the [demo](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/App.xaml)?

**Comment by cpyfferoen** [comment] 2019-01-25 15:51
The Extensions App.xaml has three things in it (ignoring colors), in this order
1. MaterialDesignThemes Defaults
2. MaterialDesignThemes Light (via Extensions Light theme)
3. Extensions Generic (via Extensions Light theme)

I've exceeded this by directly including more than I should need. I believe the order matters, perhaps I have them in a wrong order. I haven't directly tried to replace my app.xaml with the demo one. If I do I'll report back.

**Comment by HedpE-** [comment] 2019-02-22 03:04
Hi all, I fixed this issue by adding a reference to the MaterialDesignTheme.Defaults.xaml on my root control.
I think this would be fixed to everyone if the FileSystemControlTemplates.xaml forced the MaterialDesignTheme.Defaults.xaml or the independent controls references.

**Comment by spiegelp** [comment] 2019-05-19 10:14
To everybody with the exception
`Cannot find resource named 'MaterialDesignComboBox'. Resource names are case sensitive`

Please see issue #28 and post to it to avoid duplicates.

**Closed by spiegelp** 2019-05-19 10:14 UTC
Labels: help wanted

**Comment by maxmontgmx** [comment] 2020-01-09 12:43
Hi all,
I get a similar issue, but the inner exception is different.
I'm using : 
  <package id="MaterialDesignColors" version="1.2.1" targetFramework="net46" />
  <package id="MaterialDesignExtensions" version="2.8.0" targetFramework="net462" />
  <package id="MaterialDesignThemes" version="3.0.0" targetFramework="net46" />

The expection detail is : 
System.Windows.Media.Animation.AnimationException
  HResult=0x80131501
  Message=Impossible d'animer la propriété sur un(e) 'IsOpen' d'un(e) 'ControlzEx.PopupEx' à l'aide d'un(e) 'System.Windows.Media.Animation.BooleanAnimationUsingKeyFrames'. Pour plus d'informations, consultez l'exception interne.
  Source=PresentationCore
  Arborescence des appels de procédure :
   à System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   à System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   à System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   à System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   à System.Windows.Media.Animation.TimeManager.Tick()
   à System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   à System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à System.Windows.Application.Run(Window window)
   à System.Windows.Application.Run()
   à TestSupervisor.App.Main()

Exception interne 1 :
XamlParseException : L'initialisation de 'MaterialDesignExtensions.Controls.OpenFileControl' a levé une exception.

Exception interne 2 :
NotImplementedException : La méthode ou l'opération n'est pas implémentée.


Thanks for yor help
