### ISSUE TITLE
How to programmatically switch tabs stepper?

### ISSUE THREAD

**Issue by Henisk** [spiegelp/MaterialDesignExtensions#123] opened 2020-11-30 11:15 UTC
Hello, how do I programmatically switch tabs? 
SelectedIndex shows current tab but cannot set. The index is changing but there is no reaction.
sorry for my English. Thanks!

**Comment by spiegelp** [comment] 2020-11-30 21:54
Duplicate of #117

**Closed by spiegelp** 2020-11-30 21:54 UTC
