### ISSUE TITLE
Feedback during use

### ISSUE THREAD

**Issue by myn724405566** [spiegelp/MaterialDesignExtensions#101] opened 2020-07-07 03:26 UTC
My dear friend, you must declare the limitation of the reflected attribute, otherwise the result obtained is null
![image](https://user-images.githubusercontent.com/23432448/86701300-7b781d80-c044-11ea-903c-02e70511f293.png)

**Comment by spiegelp** [comment] 2020-07-21 20:10
@myn724405566 Thank you for the hint. The issue is going to be fixed with the next release.

**Closed by spiegelp** 2020-07-21 20:10 UTC
